### PR TITLE
New page successfully displays recipes

### PR DESCRIPTION
**Pull request by Hemz1416**

### CODE REVIEW

**Comment by Samyukta-b** [comment]
hi can you mention which url you would liek me to run to be able to view the display page?

**Comment by Samyukta-b** [comment]
@Hemz1416 hello?

**Comment by Samyukta-b** [comment]
@Hemz1416 hello? were you able to make it work

**Comment by Hemz1416** [comment]
@Samyukta-b  its saying unable to access github/Delta18-Git/.. cuz its not my repo

**Comment by Hemz1416** [comment]
give me 10 mins i got the fix.

**Comment by Samyukta-b** [comment]
@Hemz1416 i'm sorry, but i'm getting errors, i will be deassigning you. i will give you 75 points for your efforts. thank you for working on this issue

**Comment by Samyukta-b** [comment]
!bounty 75

**Pull request closed without merging**
