### PR TITLE
NEW page

### PR DESCRIPTION
**Pull request by stealthwhizz**

### CODE REVIEW

**Comment by Samyukta-b** [comment]
it's giving errors , please make sure the code follows MVC structure. It needs to be RecipeModel instead of just Model. please also check regardign the addAttribute fucntion. also mention how you would like the display to be viewed. mention the url you want me to run to check the display

**Comment by Samyukta-b** [comment]
okay i'll check now

**Comment by Samyukta-b** [comment]
what is the url you would like me to run to see the display page?

**Comment by Samyukta-b** [comment]
okay i need you to move the recipes.html under the static folder, also can you display data from the database in the display page too? not just the headings

**Comment by Samyukta-b** [comment]
create your own data using the form and have it be displayed on the display page

**Review by stealthwhizz — COMMENTED** [review]
http://localhost:8080/user/recipe/view

**Comment by Samyukta-b** [comment]
you have removed the /add endpoint which is the main endpoint that saves recipes in the database. the rate and the delete functions should be present on the display page as well. if you can add a notification on the form page when a recipe gets saved, to let the user know tat the recipe has been saved, i can give you extra bounty : 50

**Comment by stealthwhizz** [comment]
> you have removed the /add endpoint which is the main endpoint that saves recipes in the database. the rate and the delete functions should be present on the display page as well. if you can add a notification on the form page when a recipe gets saved, to let the user know tat the recipe has been saved, i can give you extra bounty : 50

MB MB

**Comment by stealthwhizz** [comment]
added it back

**Comment by Samyukta-b** [comment]
can you come meet me? 001 room

**Comment by stealthwhizz** [comment]
> can you come meet me? 001 room

15 mins for some reason im getting build error

**Pull request closed without merging**
