### PR TITLE
Closes #3 Try to add label support

### LINKED ISSUE #3: Implement labels/catalog support for recipes
- Modify the MongoDB structure to incorporate labels for each recipe, allowing more than one label for a recipe. (e.g., Indian, Favorite)
- Update the recipe creation form to allow users to add labels.

### PR DESCRIPTION
**Pull request by Delta18-Git**
This may work.

### CODE REVIEW

**Comment by Samyukta-b** [comment]
yes i will look into this

**Comment by Delta18-Git** [comment]
Sorry, I realised I hadn't committed all the changes. 🙏🏻

**Comment by Delta18-Git** [comment]
@Samyukta-b Please do tell me if this isn't how this works, so I can close this PR and try attempting other repos. 🙏🏻 

(Sorry for the amount of @ s)

**Comment by Samyukta-b** [comment]
hi, yes im sorrry it took a long to review this, i'm looking at it right now

**Comment by Samyukta-b** [comment]
there is an error with the RecipeMOdel where you have defined the List<string> labels. a list cannot sit in a a table, try using a join table anotation

**Comment by Delta18-Git** [comment]
This is slightly confusing to me given that ingredients is a list here, and it sits fine?

**Comment by Delta18-Git** [comment]
Does it work now @Samyukta-b ? Sorry, quite a dumb mistake.

**Comment by Delta18-Git** [comment]
Did a bit more research, would the JoinTable be used to map recipe ids to labels? If so, committing now.

**Comment by Delta18-Git** [comment]
It seems to me, if it is needed to implement JoinTable, it would need to be changed from a String list to a custom type List...

**Comment by Delta18-Git** [comment]
I think this is where the code should work, please get back if it is still broken. @Samyukta-b 🙏🏻

**Comment by Samyukta-b** [comment]
hi im working on it at the moment!

**Comment by Samyukta-b** [comment]
!bounty 300

**Comment by Samyukta-b** [comment]
i need you to do one thing actually

**Comment by Samyukta-b** [comment]
can you please add @ElementCollection just above the List<String> labels

**Comment by Samyukta-b** [comment]
and update the PR again

**Comment by Delta18-Git** [comment]
That's what I did though, 
image

**Comment by Samyukta-b** [comment]
hmm okay than, thanks

**Comment by Delta18-Git** [comment]
🙏🏻

**Comment by DedLad** [comment]
!bounty 80

**Pull request merged**
