### PR TITLE
new_page

### PR DESCRIPTION
**Pull request by Viprakshi**

### CODE REVIEW

**Comment by Samyukta-b** [comment]
@Viprakshi hi, what is the url you want me to run to check the search page?

**Comment by Samyukta-b** [comment]
@Viprakshi hello?

**Comment by Viprakshi** [comment]
http://localhost:8080/search_recipes.html

**Comment by Samyukta-b** [comment]
okay give me some time to look at it

**Comment by Samyukta-b** [comment]
hi i'm getting errors can you please check. i would liek you to keep the search html file inside the static folder. you'll also need to create an endpoint to call this

**Comment by Samyukta-b** [comment]
@Viprakshi hi i'd like an update??

**Pull request closed without merging**
